export interface Bill {
  id: string;
  vendor: string;
  logo: string;
  amount: number;
  averageAmount?: number;
  dueDate: Date;
  status: 'pending' | 'paid' | 'overdue' | 'scheduled' | 'paused' | 'pending_approval';
  category: 'utilities' | 'subscription' | 'insurance' | 'rent' | 'other';
  isAutoPay: boolean;
  description?: string;
  isUrgent?: boolean;
  // Extended fields for production-ready billing
  invoiceNumber?: string;
  ocr?: string;
  bankgiro?: string;
  isDuplicate?: boolean;
  duplicateOf?: string;
  priceIncrease?: {
    percentageChange: number;
    absoluteChange: number;
    reason?: string;
  };
  paidAt?: Date;
  paymentMethod?: string;
  scheduledAt?: Date;
  /** Risk score 0-100 generated by ClarityEngine */
  riskScore?: number;
}

export type UserRole = 'owner' | 'parent' | 'junior' | 'member';

export interface User {
  id: string;
  name: string;
  firstName: string;
  email: string;
  isAutoPilotEnabled: boolean;
  // Financial data
  monthlyIncome?: number;
  savingsGoalPercent?: number; // Default 20%
  incomeDay?: number; // Day of month salary arrives, default 25
  currentBalance?: number;
  savingsBalance?: number;
  // Family Connect fields
  familyId?: string;
  userRole?: UserRole;
  parentUserId?: string; // For junior accounts
  linkedAccounts?: string[]; // For parent accounts
  // Preferences
  preferredLanguage?: 'sv' | 'en';
  notificationsEnabled?: boolean;
  biometricEnabled?: boolean;
  darkMode?: 'light' | 'dark' | 'system';
  payday?: number;
}

export interface PaymentMethod {
  id: string;
  type: 'apple_pay' | 'card' | 'bank' | 'autogiro' | 'swish';
  name?: string;
  last4?: string;
  expiryMonth?: number;
  expiryYear?: number;
  bankName?: string;
  accountNumber?: string;
  isDefault: boolean;
  isVerified?: boolean;
}

export interface Subscription {
  id: string;
  vendor: string;
  logo: string;
  amount: number;
  frequency: 'monthly' | 'quarterly' | 'yearly' | 'weekly';
  nextBillingDate: Date;
  category: 'utilities' | 'subscription' | 'insurance' | 'rent' | 'other';
  description?: string;
  isActive: boolean;
  startDate?: Date;
  usageScore: number; // 0-1
  recommendation: 'keep' | 'review' | 'cancel';
  warning?: string;
  isDuplicate?: boolean;
  potentialSavings?: number;
}

export type NotificationType = 'due_soon' | 'overdue' | 'price_increase' | 'savings_milestone' | 'autopilot_action' | 'family' | 'deviation' | 'budget_warning' | 'general';

export interface Notification {
  id: string;
  type: NotificationType;
  title: string;
  message: string;
  createdAt: Date;
  isRead: boolean;
  isDismissed: boolean;
  actionRoute?: string;
  actionParams?: Record<string, unknown>;
  priority: 'low' | 'medium' | 'high' | 'critical';
  icon?: string;
  amount?: number;
}

export interface Budget {
  id: string;
  category: Bill['category'] | 'all';
  limit: number;
  spent: number;
  period: 'monthly' | 'yearly';
  alertThreshold: number; // 0-1 fraction, default 0.8
}

export interface Transaction {
  id: string;
  billId?: string;
  vendor: string;
  amount: number;
  date: Date;
  status: 'completed' | 'failed' | 'pending' | 'refunded';
  method: string;
  type: 'payment' | 'refund' | 'subscription' | 'savings';
  description?: string;
}

export interface FamilyMember {
  id: string;
  name: string;
  email?: string;
  role: UserRole;
  avatar?: string;
  isActive: boolean;
  monthlyIncome?: number;
  spendingLimit?: number;
  joinedAt: Date;
}

export interface Family {
  id: string;
  name: string;
  ownerId: string;
  members: FamilyMember[];
  sharedBudgets?: Budget[];
  createdAt: Date;
}

export interface Insight {
  id: string;
  type: 'saving' | 'warning' | 'opportunity' | 'celebration' | 'tip';
  title: string;
  description: string;
  amount?: number;
  impact?: 'low' | 'medium' | 'high';
  actionText?: string;
  actionRoute?: string;
  isDismissed: boolean;
  createdAt: Date;
}

export interface Achievement {
  id: string;
  title: string;
  description: string;
  icon: string;
  unlockedAt?: Date;
  progress: number;
  target: number;
  isUnlocked: boolean;
}
